### ISSUE TITLE
Question about the waterproofing

### ISSUE THREAD

**Issue by Kinnay21** [ruuvi/mechanics#1]
I noticed that your RuuvyTag is certified IP67. I guess it’s due to the seal on the enclosure base.
But I don’t understand how you can measure the extern humidity? What do you use to allow the humidity to enter inside the enclosure without letting water enter too?
I see a little hole in the enclosure lid. What do you use to close this hole?

**Comment by rambo** [comment]
There is a goretex-style membrane inside that will let air pass but not water.
